// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelError ds error
//
// swagger:ds ds.Error
type ErrRespType string

const (
	TypeClientReq   ErrRespType = "Client error"
	TypeInternalReq ErrRespType = "Internal"
	Err400          ErrRespType = "Bad Request"
	Err404          ErrRespType = "Not Found"
	Err500          ErrRespType = "Internal Server Error"
)

type StoreError struct {

	// description
	Description string `json:"description,omitempty"`

	// error
	Error ErrRespType `json:"error,omitempty"`

	// type
	Type ErrRespType `json:"type,omitempty"`
}

// Validate validates this ds error
func (m *StoreError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ds error based on context it is used
func (m *StoreError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoreError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoreError) UnmarshalBinary(b []byte) error {
	var res StoreError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
