// Code generated by go-swagger; DO NOT EDIT.

package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelNewsUpdated ds news updated
//
// swagger:ds ds.NewsUpdated
type StoreCreated struct {

	// success
	Success bool `json:"created,omitempty"`
}

// Validate validates this ds news updated
func (m *StoreCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ds news updated based on context it is used
func (m *StoreCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoreCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoreCreated) UnmarshalBinary(b []byte) error {
	var res StoreCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
