// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sergey Nekrasov",
            "url": "https://vk.com/serega_nekrasov",
            "email": "79508031750@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/promos/change/price": {
            "put": {
                "description": "Change the promo price using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Change"
                ],
                "summary": "Change promo price",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID промо",
                        "name": "UUID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Новая цена",
                        "name": "Price",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoChanged"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    }
                }
            }
        },
        "/promos/create": {
            "post": {
                "description": "Adding a new promo to database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Add"
                ],
                "summary": "Add a new promo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Магазин",
                        "name": "Store",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Скидка",
                        "name": "Discount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Цена",
                        "name": "Price",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Количество",
                        "name": "Quantity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "Промокоды(запись в виде массива)",
                        "name": "Promo",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoCreated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    }
                }
            }
        },
        "/promos/create/random": {
            "post": {
                "description": "Adding a new random promo to database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Add"
                ],
                "summary": "Add a new random promo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Количество",
                        "name": "Quantity",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoCreated"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    }
                }
            }
        },
        "/promos/delete": {
            "delete": {
                "description": "Delete a promo using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Delete"
                ],
                "summary": "Delete a promo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID промо",
                        "name": "UUID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoDeleted"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    }
                }
            }
        },
        "/promos/get": {
            "get": {
                "description": "Get a list of all promos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get all records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PromosDocs"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/promos.PromoError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.PromosDocs": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "promo": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "quantity": {
                    "type": "integer"
                },
                "store": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "promos.PromoChanged": {
            "type": "object",
            "properties": {
                "changed": {
                    "type": "boolean"
                }
            }
        },
        "promos.PromoCreated": {
            "type": "object",
            "properties": {
                "created": {
                    "description": "success",
                    "type": "boolean"
                }
            }
        },
        "promos.PromoDeleted": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                }
            }
        },
        "promos.PromoError": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "description",
                    "type": "string"
                },
                "error": {
                    "description": "error",
                    "type": "string"
                },
                "type": {
                    "description": "type",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Freebie-shop",
	Description:      "Store with promo codes for various stores",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
