// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sergey Nekrasov",
            "url": "https://vk.com/serega_nekrasov",
            "email": "79508031750@yandex.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart": {
            "get": {
                "description": "Get a list of the entire basket",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get a whole cart",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Cart"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/cart/decrease/{Store}": {
            "get": {
                "description": "Decrease by 1 the number of promo codes in the cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Decrease by 1 in the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Магазин",
                        "name": "Store",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.CartDecrease"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/cart/delete/{Store}": {
            "delete": {
                "description": "Delete a store in the cart using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Delete"
                ],
                "summary": "Delete a store in the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Магазин",
                        "name": "Store",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.Delete"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/cart/increase/{Store}": {
            "get": {
                "description": "Increase by 1 the number of promo codes in the cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Increase by 1 in the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Магазин",
                        "name": "Store",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.CartIncrease"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/cart/{Store}": {
            "get": {
                "description": "Get one store from the shopping cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get store from the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Магазин",
                        "name": "Store",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Cart"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/store": {
            "get": {
                "description": "Get a list of all stores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get all stores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.StoreDocs"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Adding a new promo to database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Add"
                ],
                "summary": "Add a new promo",
                "parameters": [
                    {
                        "description": "Магазин",
                        "name": "Promo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.StoreDocs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/swagger.Create"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/store/random": {
            "post": {
                "description": "Adding a new random promo to database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Add"
                ],
                "summary": "Add a new random promo",
                "parameters": [
                    {
                        "description": "Количество",
                        "name": "Quantity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.QuantityStores"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/swagger.Create"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/store/{UUID}": {
            "get": {
                "description": "Get store using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get store",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID магазина",
                        "name": "UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.StoreDocs"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Change the promo price using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Change"
                ],
                "summary": "Change promo price",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID магазина",
                        "name": "UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новая цена",
                        "name": "Price",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.PriceStore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.Change"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a store using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Delete"
                ],
                "summary": "Delete a store",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID магазина",
                        "name": "UUID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.Delete"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        },
        "/store/{UUID}/{Quantity}": {
            "get": {
                "description": "Get a promo in store using its uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get a promo",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "UUID магазина",
                        "name": "UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Кол-во",
                        "name": "Quantity",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.StorePromo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ds.Cart": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer",
                    "example": 3
                },
                "store": {
                    "type": "string",
                    "example": "976c088c-f218-422b-aff6-f9e1cf792860"
                }
            }
        },
        "ds.PriceStore": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer",
                    "example": 300
                }
            }
        },
        "ds.QuantityStores": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "ds.StoreDocs": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "integer",
                    "example": 400
                },
                "image": {
                    "type": "string",
                    "example": "https://res.cloudinary.com/dh4qv3hob/image/upload/v1667665906/Promos/Five_gioiio.png"
                },
                "name": {
                    "type": "string",
                    "example": "Пятёрочка"
                },
                "price": {
                    "type": "integer",
                    "example": 200
                },
                "promo": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "djzML",
                        "MdUI7",
                        "byP1f"
                    ]
                },
                "quantity": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "swagger.CartDecrease": {
            "type": "object",
            "properties": {
                "promo": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "swagger.CartIncrease": {
            "type": "object",
            "properties": {
                "promo": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "swagger.Change": {
            "type": "object",
            "properties": {
                "changed": {
                    "type": "boolean"
                }
            }
        },
        "swagger.Create": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                }
            }
        },
        "swagger.Delete": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                }
            }
        },
        "swagger.Error": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "swagger.StorePromo": {
            "type": "object",
            "properties": {
                "promo": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "gR3hr"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Freebie-shop",
	Description:      "Store with promo codes for various stores",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
