basePath: /
definitions:
  model.PromosDocs:
    properties:
      discount:
        type: integer
      price:
        type: integer
      promo:
        items:
          type: string
        type: array
      quantity:
        type: integer
      store:
        type: string
      uuid:
        type: string
    type: object
  promos.PromoChanged:
    properties:
      changed:
        type: boolean
    type: object
  promos.PromoCreated:
    properties:
      created:
        description: success
        type: boolean
    type: object
  promos.PromoDeleted:
    properties:
      deleted:
        type: boolean
    type: object
  promos.PromoError:
    properties:
      description:
        description: description
        type: string
      error:
        description: error
        type: string
      type:
        description: type
        type: string
    type: object
  promos.PromoPrice:
    properties:
      price:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: 79508031750@yandex.ru
    name: Sergey Nekrasov
    url: https://vk.com/serega_nekrasov
  description: Store with promo codes for various stores
  title: Freebie-shop
  version: "1.0"
paths:
  /promos:
    get:
      description: Get a list of all promos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PromosDocs'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/promos.PromoError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/promos.PromoError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Get all records
      tags:
      - Info
  /promos/:
    post:
      description: Adding a new promo to database
      parameters:
      - description: Магазин
        in: query
        name: Store
        required: true
        type: string
      - description: Скидка
        in: query
        name: Discount
        required: true
        type: integer
      - description: Цена
        in: query
        name: Price
        required: true
        type: integer
      - description: Количество
        in: query
        name: Quantity
        required: true
        type: integer
      - description: Промокоды(запись в виде массива)
        in: query
        items:
          type: string
        name: Promo
        required: true
        type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/promos.PromoCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/promos.PromoError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/promos.PromoError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Add a new promo
      tags:
      - Add
  /promos/:uuid:
    delete:
      description: Delete a promo using its uuid
      parameters:
      - description: UUID промо
        format: uuid
        in: query
        name: UUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promos.PromoDeleted'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/promos.PromoError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/promos.PromoError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Delete a promo
      tags:
      - Delete
    get:
      description: Get the price using the promo uuid
      parameters:
      - description: UUID промо
        format: uuid
        in: query
        name: UUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promos.PromoPrice'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Get price for a promo
      tags:
      - Info
  /promos/:uuid/:price:
    put:
      description: Change the promo price using its uuid
      parameters:
      - description: UUID промо
        format: uuid
        in: query
        name: UUID
        required: true
        type: string
      - description: Новая цена
        in: query
        name: Price
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/promos.PromoChanged'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/promos.PromoError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/promos.PromoError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Change promo price
      tags:
      - Change
  /promos/random:
    post:
      description: Adding a new random promo to database
      parameters:
      - description: Количество
        in: query
        name: Quantity
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/promos.PromoCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/promos.PromoError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/promos.PromoError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/promos.PromoError'
      summary: Add a new random promo
      tags:
      - Add
schemes:
- http
- https
swagger: "2.0"
